- name: Add apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:tista/adapta
    - ppa:papirus/papirus
    - ppa:lazygit-team/release
    - ppa:unity7maintainers/unity7-desktop

- name: Add packagecloud apt key (for gbt)
  become: yes
  apt_key:
    url: https://packagecloud.io/gbt/release/gpgkey

- name: Add gbt.list apt source list
  become: yes
  copy:
    src: gbt.list
    dest: /etc/apt/sources.list.d/gbt.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - adapta-backgrounds
    - adapta-gtk-theme
    - ansible
    - budgie-desktop-environment
    - curl
    - gbt
    - gcc
    - git
    - htop
    - lazygit
    - make
    - papirus-icon-theme
    - pkg-config
    - python3-dev
    - python3-pip
    - python3-venv
    - python-dev
    - python-pip
    - ranger
    - silversearcher-ag
    - slick-greeter
    - tmux
    - tree
    - unity-settings-daemon
    - unzip
    - vim
    - xclip
    - zsh
    - zsh-syntax-highlighting
