- name: Copy configs
  copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
  loop:
    - .zshrc
    - .zsh_aliases
    - .gitconfig
    - .tmux.conf
    - .vimrc
    - .custom_envs.zsh

- name: Ensure gtk dir exists
  file:
    path: /home/{{ user }}/.config/gtk-3.0
    state: directory
    recurse: yes

- name: Copy gtk3 settings
  copy:
    src: settings.ini
    dest: /home/{{ user }}/.config/gtk-3.0/settings.ini
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Ensure budgie-desktop dir exists
  file:
    path: /home/{{ user }}/.config/budgie-desktop
    state: directory
    recurse: yes

- name: Check if budgie firstrun file exists
  stat:
    path: /home/{{ user }}/.config/budgie-desktop/firstrun
  register: firstrun_check
  changed_when: false

- name: Ensure budgie firstrun files exist
  file:
    path: /home/{{ user }}/.config/budgie-desktop/{{ item }}
    state: touch
  with_items:
    - firstrun
    - firstruncommon
    - keycontrol2
  when: firstrun_check.stat.exists == False
