- name: Check if bat is installed
  shell: command -v bat >/dev/null 2>&1
  register: bat_check
  changed_when: false
  failed_when: false

- name: Install bat
  become: yes
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.9.0/bat_0.9.0_amd64.deb
  when: bat_check.rc != 0
