- name: Check if diff-so-fancy is installed
  shell: command -v diff-so-fancy >/dev/null 2>&1
  register: diff_so_fancy_check
  changed_when: false
  failed_when: false

- name: Install diff-so-fancy
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: /usr/local/bin/diff-so-fancy
    mode: 0755
  when: diff_so_fancy_check.rc != 0
