- name: Check if ripgrep is installed
  shell: command -v ripgrep >/dev/null 2>&1
  register: ripgrep_check
  changed_when: false
  failed_when: false

- name: Install ripgrep
  become: yes
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.debbat
  when: ripgrep_check.rc != 0
