- name: Copy .bashrc
  copy:
    src: .bashrc
    dest: /home/planeta/.bashrc
    owner: planeta
    group: planeta
    mode: u=rw,g=r,o=r

- name: Copy .gitconfig
  copy:
    src: .gitconfig
    dest: /home/planeta/.gitconfig
    owner: planeta
    group: planeta
    mode: u=rw,g=r,o=r
