- name: Copy .bashrc
  copy:
    src: .bashrc
    dest: /home/planeta/.bashrc
    owner: planeta
    group: planeta
    mode: u=rw,g=r,o=r

- synchronize: Synchronize .config directory
    src: .config
    dest: /home/planeta/.config
