- name: Copy .zshrc
  copy:
    src: .zshrc
    dest: /home/{{ user }}/.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Copy .gitconfig
  copy:
    src: .gitconfig
    dest: /home/{{ user }}/.gitconfig
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Copy .tmux.conf
  copy:
    src: .tmux.conf
    dest: /home/{{ user }}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Ensure gtk dir exists
  file:
    path: /home/{{ user }}/.config/gtk-3.0
    state: directory
    recurse: yes

- name: Copy gtk3 settings
  copy:
    src: settings.ini
    dest: /home/{{ user }}/.config/gtk-3.0/settings.ini
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Ensure budgie-desktop dir exists
  file:
    path: /home/{{ user }}/.config/budgie-desktop
    state: directory
    recurse: yes

- name: Ensure budgie firstrun files exist
  file:
    path: /home/{{ user }}/.config/budgie-desktop/{{ item }}
    state: touch
  with_items:
    - firstrun
    - firstruncommon
    - keycontrol2
