- name: Copy .zshrc
  copy:
    src: .zshrc
    dest: /home/{{ user }}/.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Copy .gitconfig
  copy:
    src: .gitconfig
    dest: /home/{{ user }}/.gitconfig
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: Copy .tmux.conf
  copy:
    src: .tmux.conf
    dest: /home/{{ user }}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
