- name: Copy .bashrc
  copy:
    src: .bashrc
    dest: /home/planeta/.bashrc
    owner: planeta
    group: planeta
    mode: u=rw,g=r,o=r

    #- name: Synchronize .config directory
    #  synchronize: 
    #    src: .config
    #    dest: /home/planeta/.config
