- name: Install lightdm apt package
  apt:
    name: lightdm
    state: present
  become: yes
  become_method: sudo

- name: Reconfigure dpkg
  command: dpkg-reconfigure -f noninteractive lightdm
  become: yes
  become_method: sudo
