- name: Install lightdm apt package
  become: yes
  apt:
    name: lightdm
    state: present

- name: Remove gdm3 apt package
  become: yes
  apt:
    name: gdm3
    state: absent

- name: Reconfigure dpkg
  become: yes
  command: dpkg-reconfigure -f noninteractive lightdm

- name: Copy 50-budgie.conf
  become: yes
  copy:
    src: 50-budgie.conf
    dest: /etc/lightdm/lightdm.conf.d/50-budgie.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy lightdm.conf
  become: yes
  copy:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy slick-greeter.conf
  become: yes
  copy:
    src: slick-greeter.conf
    dest: /etc/lightdm/slick-greeter.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy wallpaper
  become: yes
  copy:
    src: "{{ wallpaper }}"
    dest: /usr/share/backgrounds/{{ wallpaper }}
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Set gsettings
  command: gsettings set {{item}}
  with_items:
    - org.gnome.desktop.interface gtk-theme {{ theme }}
    - org.gnome.desktop.interface icon-theme {{ icon_theme }} 
    - org.gnome.desktop.wm.preferences theme {{ theme }}
    - org.gnome.desktop.background picture-uri file:///usr/share/backgrounds/{{ wallpaper }}
    - org.gnome.desktop.interface monospace-font-name '{{ monospace_font_name }} {{ monospace_font_size}}'
