- name: Install lightdm apt package
  apt:
    name: lightdm
    state: present

- name: Remove gdm3 apt package
  apt:
    name: gdm3
    state: absent

- name: Reconfigure dpkg
  command: dpkg-reconfigure -f noninteractive lightdm
