- name: Install lightdm apt package
  apt:
    name: lightdm
    state: present

- name: Remove gdm3 apt package
  apt:
    name: gdm3
    state: absent

- name: Reconfigure dpkg
  command: dpkg-reconfigure -f noninteractive lightdm

- name: Copy 50-budgie.conf
  copy:
    src: 50-budgie.conf
    dest: /etc/lightdm/lightdm.conf.d/50-budgie.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
