- name: Install lightdm apt package
  apt:
    name: lightdm
    state: present

- name: Remove gdm3 apt package
  apt:
    name: gdm3
    state: absent

- name: Reconfigure dpkg
  command: dpkg-reconfigure -f noninteractive lightdm

- name: Copy 50-budgie.conf
  copy:
    src: 50-budgie.conf
    dest: /etc/lightdm/lightdm.conf.d/50-budgie.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy lightdm.conf
  copy:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy slick-greeter.conf
  copy:
    src: slick-greeter.conf
    dest: /etc/lightdm/slick-greeter.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy wallpaper
  copy:
    src: minimalist-city.jpg 
    dest: /usr/share/backgrounds/minimalist-city.jpg
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Set gsettings
  command: gsettings set {{item}}
  with_items:
    - org.gnome.desktop.interface gtk-theme Adapta
    - org.gnome.desktop.interface icon-theme Papirus
    - org.gnome.desktop.wm.preferences theme Adapta
    - org.gnome.desktop.background picture-uri file:///usr/share/backgrounds/minimalist-city.jpg
