- name: Set gsettings
  command: gsettings set "{{item}}"
  with_items: 
    - org.gnome.desktop.interface gtk-theme Adapta
    - org.gnome.desktop.interface icon-theme Papirus
    - org.gnome.desktop.wm.preferences theme Adapta
