- name: Create configure users
  import_tasks: users.yml

- name: Install packages
  import_tasks: packages.yml

- name: Configure apps
  import_tasks: configs.yml

- name: Configure gsettings
  import_tasks: gsettings.yml
