- name: Install apt packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - vim
    - git
    - tmux
    - htop
  become: yes
  become_method: sudo

- name: Clone fzf repo
  git: 
    repo: https://github.com/junegunn/fzf.git 
    dest: /home/planeta/.fzf
    depth: 1
  become: no

- name: Install fzf
  command: /home/planeta/.fzf/install --key-bindings --completion --no-update-rc
  become: no

- name: Remove fzf repo
  file:
    path: /home/planeta/.fzf
    state: absent
  become: no
