- name: Add apt repositories
  become: true
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - ppa:tista/adapta 
    - ppa:papirus/papirus 

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install apt packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - vim
    - git
    - tmux
    - htop
    - budgie-desktop-environment
    - adapta-backgrounds
    - adapta-gtk-theme
    - papirus-icon-theme   
  become: yes
  become_method: sudo

- name: Clone fzf repo
  git: 
    repo: https://github.com/junegunn/fzf.git 
    dest: /home/planeta/.fzf
    depth: 1

- name: Install fzf
  command: /home/planeta/.fzf/install --key-bindings --completion --no-update-rc
