- name: Add apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:tista/adapta 
    - ppa:papirus/papirus 

- name: Add packagecloud apt key (for gbt)
  become: true
  apt_key:
    url: https://packagecloud.io/gbt/release/gpgkey
  
- name: Add gbt.list apt source list
  become: true
  copy:
    src: gbt.list
    dest: /etc/apt/sources.list.d/gbt.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install apt packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - vim
    - git
    - tmux
    - htop
    - zsh
    - budgie-desktop-environment
    - slick-greeter
    - adapta-backgrounds
    - adapta-gtk-theme
    - papirus-icon-theme   
    - gbt

- name: Clone fzf repo
  git: 
    repo: https://github.com/junegunn/fzf.git 
    dest: /home/{{ user }}/.fzf
    depth: 1
  become_user: "{{ user }}"

- name: Install fzf
  command: /home/{{ user }}/.fzf/install --key-bindings --completion --no-update-rc

- name: Install BitstreamVeraSansMono.zip
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/BitstreamVeraSansMono.zip
    dest: /usr/local/share/fonts
    remote_src: yes

